# Where things are
source:       .
destination:  ./docs
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
includes_dir: ./_includes

# Handling Reading
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Plugins
plugins: ['jekyll-sitemap', 'jekyll/scholar', 'jekyll-feed']

# Other configuration
timezone: Asia/Tokyo
# timezone: Asia/Ho_Chi_Minh
#encoding: utf-8

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    # Rouge Options › https://github.com/jneen/rouge#full-options
#    css_class: 'highlight'
#    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true
#      start_line: 1

# Serving
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Exclude file/folder
exclude: ['Gemfile*','Makefile','Curriculum Vitae','*.bat','*.csl','exclude_copy*','gitlab-ci.yml','README*','combinatorial-reconfiguration','travis.yml','vendor','build.sh','PGP-key.asc.enc','*.DS_Store','gitignore','dates.dat','.jekyll-cache','core.bib','docs']

# Personal information
url: http://hoanganhduc.github.io
author: Duc A. Hoang
title: Welcome to Đức's personal webpage!
auth_current_position: Postdoctoral Researcher (April 2019 - present)
email_personal: anhduc.hoang1990 [at] gmail.com
email_work: hoanganhduc [at] ces.kyutech.ac.jp
website: hoanganhduc.github.io
website_full: http://hoanganhduc.github.io
keywords: Duc A. Hoang, Hoàng Anh Đức, JAIST, Kyutech, anhduc.hoang1990, hoanganhduc, personal webpage, homepage
orcid: 0000-0002-8635-8462
institute_address: Room W609, Building 8 (Departmental Research Building), School of Computer Science and Systems Engineering, Kyushu Institute of Technology, 680-4 Kawazu, Iizuka, Fukuoka, 820-8502 Japan
interests: Graph Algorithms, <a href='http://www.ecei.tohoku.ac.jp/alg/core/'>Combinatorial Reconfiguration</a>

collections:
  posts:
    output: true
    permalink: "/blog/:year/:month/:day/:title/"
  teaching:
    output: true

feed:
  excerpt_only: true

# Jekyll-scholar configuration
scholar:

  sort_by: year
  order: asscending
  bibliography_list_tag: ol
  group_by: pubtype
  group_order: ascending

  source: ./

  replace_strings: true
  join_strings:    true

  reference_tagname: div

  bibtex_filters:
  - superscript
  - latex

  query: "@*"

